---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: settings
  name: settings
  namespace: ${NAMESPACE}
spec:
  ports:
  - name: settings
    port: 80
    targetPort: service-port
    protocol: TCP
  selector:
    app: settings
---
