on: 
  push:
    branches:
      - main
    # paths:
    #   - 'config/**'
    #   - 'site/**'
    #   - 'Dockerfile'
    #   - '.github/workflows/**'   

jobs:

  build:
    name: Build, push, and deploy
    runs-on: ubuntu-latest
    steps:

    - name: Checkout master
      uses: actions/checkout@master

    - name: Update SHA
      run: echo $GITHUB_SHA > $GITHUB_WORKSPACE/helm/notes

    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
  
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}


    - name: Build and push.
      id: docker_build
      uses: docker/build-push-action@v2
      with:
          push: true
          tags: |
            kasparov112000/learnbytesting-settings-docker:latest
            kasparov112000/learnbytesting-settings-docker:${{ github.sha }}
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.MYTOKEN }}

    - name: Save DigitalOcean kubeconfig with short-lived credentials
      run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 k8s-lbt
    
    - name: Prep helm chart
      run: |
          mv ./helm/Chart.yaml ./helm/Chart.old.yaml &&
          cat ./helm/Chart.old.yaml | grep -v appVersion > ./helm/Chart.yaml &&
          echo -e "\r\nappVersion: v${GITHUB_REF##*/}\r\n" >> ./helm/Chart.yaml &&
          cat ./helm/Chart.yaml
    - name: Install Helm
      uses: azure/setup-helm@v3
      with:
        version: 'latest'
    
    - name: Deploy
      run: |
        helm upgrade settings ./helm/ --install --wait --atomic \
          --set=image.tag=${{ github.sha }} \
          --values=./helm/values.yaml \
          --timeout=10m
